--------------------------------------------------------
-- Archivo creado  - domingo-abril-30-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CATEGORIES
--------------------------------------------------------

  CREATE TABLE "AARONP1"."CATEGORIES" 
   (	"CATEGORY_ID" NUMBER(*,0), 
	"CATEGORY_NAME" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EMPLOYEES
--------------------------------------------------------

  CREATE TABLE "AARONP1"."EMPLOYEES" 
   (	"EMPLOYEE_ID" NUMBER(*,0), 
	"FIRST_NAME" VARCHAR2(100 BYTE), 
	"LAST_NAME" VARCHAR2(100 BYTE), 
	"SALARY" NUMBER(8,2), 
	"EMAIL" VARCHAR2(50 BYTE), 
	"HIRE_DATE" DATE, 
	"PHONE_NUMBER" VARCHAR2(15 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PRODUCTS
--------------------------------------------------------

  CREATE TABLE "AARONP1"."PRODUCTS" 
   (	"PRODUCT_ID" NUMBER(*,0), 
	"CATEGORY_ID" NUMBER(*,0), 
	"PRODUCT_NAME" VARCHAR2(50 BYTE), 
	"PRICE" NUMBER(5,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into AARONP1.CATEGORIES
SET DEFINE OFF;
Insert into AARONP1.CATEGORIES (CATEGORY_ID,CATEGORY_NAME) values ('100','COFFEE');
Insert into AARONP1.CATEGORIES (CATEGORY_ID,CATEGORY_NAME) values ('200','DRINK');
Insert into AARONP1.CATEGORIES (CATEGORY_ID,CATEGORY_NAME) values ('300','FOOD');
REM INSERTING into AARONP1.EMPLOYEES
SET DEFINE OFF;
Insert into AARONP1.EMPLOYEES (EMPLOYEE_ID,FIRST_NAME,LAST_NAME,SALARY,EMAIL,HIRE_DATE,PHONE_NUMBER) values ('1','John','Doe','50000','johndoe@email.com',to_date('01/01/22','DD/MM/RR'),'555-1234');
Insert into AARONP1.EMPLOYEES (EMPLOYEE_ID,FIRST_NAME,LAST_NAME,SALARY,EMAIL,HIRE_DATE,PHONE_NUMBER) values ('2','Jane','Smith','60000','janesmith@email.com',to_date('01/02/22','DD/MM/RR'),'555-5678');
Insert into AARONP1.EMPLOYEES (EMPLOYEE_ID,FIRST_NAME,LAST_NAME,SALARY,EMAIL,HIRE_DATE,PHONE_NUMBER) values ('3','Bob','Johnson','55000','bobjohnson@email.com',to_date('01/03/22','DD/MM/RR'),'555-9876');
Insert into AARONP1.EMPLOYEES (EMPLOYEE_ID,FIRST_NAME,LAST_NAME,SALARY,EMAIL,HIRE_DATE,PHONE_NUMBER) values ('4','Alice','Williams','70000','alicewilliams@email.com',to_date('01/04/22','DD/MM/RR'),'555-5555');
Insert into AARONP1.EMPLOYEES (EMPLOYEE_ID,FIRST_NAME,LAST_NAME,SALARY,EMAIL,HIRE_DATE,PHONE_NUMBER) values ('5','Michael','Brown','80000','michaelbrown@email.com',to_date('01/05/22','DD/MM/RR'),'555-4321');
Insert into AARONP1.EMPLOYEES (EMPLOYEE_ID,FIRST_NAME,LAST_NAME,SALARY,EMAIL,HIRE_DATE,PHONE_NUMBER) values ('6','Jennifer','Davis','65000','jenniferdavis@email.com',to_date('01/06/22','DD/MM/RR'),'555-2468');
Insert into AARONP1.EMPLOYEES (EMPLOYEE_ID,FIRST_NAME,LAST_NAME,SALARY,EMAIL,HIRE_DATE,PHONE_NUMBER) values ('7','Robert','Anderson','75000','robertanderson@email.com',to_date('01/07/22','DD/MM/RR'),'555-1111');
Insert into AARONP1.EMPLOYEES (EMPLOYEE_ID,FIRST_NAME,LAST_NAME,SALARY,EMAIL,HIRE_DATE,PHONE_NUMBER) values ('8','Emily','Taylor','90000','emilytaylor@email.com',to_date('01/08/22','DD/MM/RR'),'555-3333');
Insert into AARONP1.EMPLOYEES (EMPLOYEE_ID,FIRST_NAME,LAST_NAME,SALARY,EMAIL,HIRE_DATE,PHONE_NUMBER) values ('9','David','Martinez','60000','davidmartinez@email.com',to_date('01/09/22','DD/MM/RR'),'555-7777');
Insert into AARONP1.EMPLOYEES (EMPLOYEE_ID,FIRST_NAME,LAST_NAME,SALARY,EMAIL,HIRE_DATE,PHONE_NUMBER) values ('10','Sarah','Garcia','55000','sarahgarcia@email.com',to_date('01/10/22','DD/MM/RR'),'555-8888');
REM INSERTING into AARONP1.PRODUCTS
SET DEFINE OFF;
Insert into AARONP1.PRODUCTS (PRODUCT_ID,CATEGORY_ID,PRODUCT_NAME,PRICE) values ('101','100','COFFEE1','1,99');
Insert into AARONP1.PRODUCTS (PRODUCT_ID,CATEGORY_ID,PRODUCT_NAME,PRICE) values ('102','100','COFFEE2','0,99');
Insert into AARONP1.PRODUCTS (PRODUCT_ID,CATEGORY_ID,PRODUCT_NAME,PRICE) values ('103','100','COFFEE3','1,5');
Insert into AARONP1.PRODUCTS (PRODUCT_ID,CATEGORY_ID,PRODUCT_NAME,PRICE) values ('201','200','DRINK1','1,99');
Insert into AARONP1.PRODUCTS (PRODUCT_ID,CATEGORY_ID,PRODUCT_NAME,PRICE) values ('202','200','DRINK2','1,5');
Insert into AARONP1.PRODUCTS (PRODUCT_ID,CATEGORY_ID,PRODUCT_NAME,PRICE) values ('203','200','DRINK3','1');
Insert into AARONP1.PRODUCTS (PRODUCT_ID,CATEGORY_ID,PRODUCT_NAME,PRICE) values ('301','300','FOOD1','2,99');
Insert into AARONP1.PRODUCTS (PRODUCT_ID,CATEGORY_ID,PRODUCT_NAME,PRICE) values ('302','300','FOOD2','3,99');
Insert into AARONP1.PRODUCTS (PRODUCT_ID,CATEGORY_ID,PRODUCT_NAME,PRICE) values ('303','300','FOOD3','4,99');
--------------------------------------------------------
--  Constraints for Table EMPLOYEES
--------------------------------------------------------

  ALTER TABLE "AARONP1"."EMPLOYEES" ADD PRIMARY KEY ("EMPLOYEE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CATEGORIES
--------------------------------------------------------

  ALTER TABLE "AARONP1"."CATEGORIES" ADD PRIMARY KEY ("CATEGORY_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PRODUCTS
--------------------------------------------------------

  ALTER TABLE "AARONP1"."PRODUCTS" ADD PRIMARY KEY ("PRODUCT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "AARONP1"."PRODUCTS" MODIFY ("CATEGORY_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table PRODUCTS
--------------------------------------------------------

  ALTER TABLE "AARONP1"."PRODUCTS" ADD CONSTRAINT "FK_PRODUCTS_CATEGORY_ID" FOREIGN KEY ("CATEGORY_ID")
	  REFERENCES "AARONP1"."CATEGORIES" ("CATEGORY_ID") ENABLE;
